interface Template {
  inicio: string[];
  meio: string[];
  fim: string[];
  cta: string[];
  hashtags: string[];
}

interface TemplateMap {
  [key: string]: Template;
}

export const templates: TemplateMap = {
  'Fé': {
    inicio: [
      'Você já se perguntou por que às vezes nossa fé é testada?',
      'Em meio às tempestades da vida, a fé é nossa âncora.',
      'Assim como Pedro, às vezes duvidamos e começamos a afundar.',
      'A fé do tamanho de um grão de mostarda pode mover montanhas.',
      'Quando tudo parece impossível, a fé abre caminhos.',
      'Na jornada da fé, cada passo conta.',
      'Sua fé tem o poder de mudar realidades.',
      'Às vezes Deus permite a prova para fortalecer nossa fé.',
      'A fé nos faz ver além das circunstâncias.',
      'Quando a fé fala, os problemas se calam.',
      'A fé é a certeza daquilo que esperamos.',
      'Em tempos de incerteza, a fé nos mantém firmes.',
      'Sua fé pode mover montanhas espirituais.',
      'A fé é a chave que abre portas impossíveis.',
      'Quando tudo falha, a fé permanece.',
      'A fé nos conecta ao sobrenatural.',
      'Sua fé é mais preciosa que ouro.',
      'A fé nos dá olhos para ver o invisível.',
      'Na escola da fé, aprendemos a confiar.',
      'A fé é nossa vitória que vence o mundo.'
    ],
    meio: [
      'Mas é justamente nesses momentos que Deus mais age em nossas vidas.',
      'É no silêncio que aprendemos a confiar mais em Deus.',
      'Jesus sempre estende Sua mão para nos resgatar.',
      'Nossa fé cresce quando enfrentamos desafios com confiança.',
      'Deus nunca nos abandona, mesmo quando não sentimos Sua presença.',
      'A fé nos mantém firmes quando tudo parece desmoronar.',
      'Cada prova é uma oportunidade de fortalecer nossa fé.',
      'Na escola da fé, as lições são diárias.',
      'A fé nos conecta ao sobrenatural de Deus.',
      'Quando cremos, o impossível se torna realidade.',
      'A fé nos permite ver a mão de Deus agindo.',
      'Nossa fé é refinada nas provações.',
      'Deus honra a fé que persevera.',
      'A fé nos mantém de pé nas tempestades.',
      'Através da fé, vemos milagres acontecerem.',
      'Nossa fé cresce quando exercitada.',
      'A fé nos dá força para continuar.',
      'Deus se agrada da nossa fé sincera.',
      'A fé nos conecta ao coração do Pai.',
      'Nossa fé é a prova do amor de Deus.'
    ],
    fim: [
      'A fé não é ausência de medo, mas confiança em meio às dificuldades.',
      'Permita que sua fé seja maior que seus medos.',
      'Confie no tempo de Deus, Ele tem o melhor plano.',
      'Sua história de fé pode inspirar outros a não desistirem.',
      'Quando confiamos em Deus, o impossível se torna possível.',
      'Sua fé pode mover as montanhas da sua vida.',
      'Continue crendo, o milagre está a caminho.',
      'A fé é a certeza daquilo que ainda não vemos.',
      'Sua fé é mais preciosa que ouro refinado.',
      'Mantenha sua fé viva e ardente.',
      'Sua fé é o testemunho do poder de Deus.',
      'A fé nos leva a lugares extraordinários.',
      'Permita que sua fé cresça cada dia mais.',
      'Sua fé é uma inspiração para muitos.',
      'Continue firme, sua fé será recompensada.',
      'A fé nos mantém focados na promessa.',
      'Sua fé tem poder para transformar vidas.',
      'A fé nos conecta ao sobrenatural.',
      'Mantenha sua fé inabalável em Deus.',
      'Sua fé é a chave para os milagres.'
    ],
    cta: [
      '👉 Que batalha você está enfrentando hoje? Confie que Deus está no controle!',
      '🙏 Compartilhe nos comentários uma situação onde sua fé foi fortalecida',
      '💫 Deus está preparando algo especial para sua vida. Continue firme!',
      '✨ Me conta: como você mantém sua fé em momentos difíceis?',
      '❤️ Marque alguém que precisa dessa mensagem hoje',
      '🌟 Qual versículo fortalece sua fé nos momentos difíceis?',
      '💪 Como você alimenta sua fé diariamente?',
      '🙌 Vamos orar juntos pelo fortalecimento da sua fé?',
      '📖 Que história bíblica mais inspira sua fé?',
      '💭 Compartilhe seu maior testemunho de fé',
      '🎯 Como sua fé tem crescido ultimamente?',
      '🌈 Que promessa de Deus você está esperando em fé?',
      '💝 Marque alguém que tem uma fé inspiradora',
      '🙏 Qual foi seu maior momento de fé?',
      '✨ Como você exercita sua fé no dia a dia?',
      '💫 Compartilhe um versículo que fortalece sua fé',
      '🌟 Que testemunho de fé você quer compartilhar?',
      '💪 Como você mantém sua fé firme nas dificuldades?',
      '🙌 Vamos declarar juntos nossa fé?',
      '❤️ Que área da sua vida precisa de mais fé?'
    ],
    hashtags: [
      '#Fé #ConfiançaEmDeus #FéEmDeus',
      '#VidaDeFé #FéInabalável #Crença',
      '#FéViva #PoderosoDeus #FéEmAção',
      '#FéESalvação #CaminharComDeus #FéVerdadeira',
      '#FéTransformadora #FéESperança #VitóriaEmDeus'
    ]
  },
  'Esperança': {
    inicio: [
      'Mesmo na noite mais escura, as estrelas ainda brilham.',
      'A esperança é a última que morre, mas em Cristo ela nunca morre.',
      'Quando tudo parece perdido, Deus renova nossas esperanças.',
      'Há sempre um novo amanhecer após a noite escura.',
      'A esperança é a certeza de que Deus está no controle.',
      'Em Cristo, nossa esperança é renovada a cada manhã.',
      'A esperança nos mantém olhando para o alto.',
      'Nunca é tarde para ter esperança em Deus.',
      'A esperança é a âncora da nossa alma.',
      'Em meio ao caos, a esperança nos guia.',
      'A esperança em Deus nunca decepciona.',
      'Nossa esperança está fundamentada nas promessas.',
      'A esperança nos dá força para continuar.',
      'Em Cristo, temos uma esperança viva.',
      'A esperança ilumina nosso caminho.',
      'Deus é a fonte da nossa esperança.',
      'A esperança nos mantém perseverando.',
      'Nossa esperança está no Senhor.',
      'A esperança renova nossas forças.',
      'Em Deus, nossa esperança é segura.'
    ],
    meio: [
      'Deus está trabalhando nos bastidores da sua vida.',
      'Os planos dEle são maiores que nossos medos.',
      'Cada novo dia é uma oportunidade de recomeçar.',
      'As promessas de Deus nunca falham.',
      'Sua história ainda não acabou, o melhor está por vir.',
      'A esperança nos mantém caminhando.',
      'Deus trabalha enquanto esperamos.',
      'Nossa espera não é em vão.',
      'A esperança fortalece nossa fé.',
      'Em Cristo, há sempre esperança.',
      'Deus renova nossa esperança diariamente.',
      'A esperança nos dá novo fôlego.',
      'Enquanto há vida, há esperança em Cristo.',
      'Nossa esperança está bem fundamentada.',
      'A esperança nos mantém focados.',
      'Deus é fiel às Suas promessas.',
      'A esperança transforma nossa perspectiva.',
      'Em Deus, encontramos nova esperança.',
      'A esperança nos faz perseverar.',
      'Nossa esperança está em Cristo.'
    ],
    fim: [
      'Mantenha seus olhos fixos em Jesus, a fonte da esperança.',
      'O que parece impossível para nós, é possível para Deus.',
      'Sua esperança em Deus nunca será em vão.',
      'Amanhã pode ser o dia da sua vitória.',
      'Deus transforma lágrimas em testemunhos.',
      'Continue esperando, Deus é fiel.',
      'A esperança em Cristo não decepciona.',
      'Seu futuro está nas mãos de Deus.',
      'A esperança nos mantém de pé.',
      'Em Cristo, há sempre um novo começo.',
      'Sua esperança será recompensada.',
      'Deus honra quem nEle espera.',
      'A esperança nos leva adiante.',
      'Continue confiando e esperando.',
      'Sua história terá um final feliz.',
      'A esperança nos dá novo ânimo.',
      'Em Deus, há sempre esperança.',
      'Sua espera não será em vão.',
      'A esperança nos fortalece.',
      'Deus é a nossa esperança viva.'
    ],
    cta: [
      '🌟 O que te dá esperança nos momentos difíceis?',
      '🙌 Compartilhe essa mensagem com alguém que precisa de esperança',
      '💭 Conte-nos: qual sonho você está esperando em Deus?',
      '✨ Sua história de esperança pode inspirar alguém hoje',
      '💪 Continue firme, Deus não desistiu de você!',
      '❤️ Como você mantém sua esperança viva?',
      '🙏 Que promessa te dá esperança hoje?',
      '💫 Compartilhe um momento de esperança renovada',
      '🌈 O que te faz manter a esperança?',
      '✨ Qual versículo te dá mais esperança?',
      '💝 Marque alguém que precisa de esperança',
      '🎯 Como você alimenta sua esperança?',
      '🌟 Que testemunho de esperança você tem?',
      '💪 Como você mantém a esperança nas dificuldades?',
      '🙌 Vamos declarar esperança juntos?',
      '❤️ Que área precisa de mais esperança?',
      '💫 Compartilhe sua maior esperança',
      '🙏 Como Deus tem renovado sua esperança?',
      '✨ Que sonho te faz manter a esperança?',
      '💭 Como você inspira esperança nos outros?'
    ],
    hashtags: [
      '#Esperança #EsperançaEmDeus #NãoDesista',
      '#EsperançaViva #DeusNoControle #Confiar',
      '#EsperançaRenovada #DeusÉFiel #NovoComeço',
      '#EsperançaEmCristo #DeusProvê #VitóriaEmDeus',
      '#EsperançaInabalável #DeusNoComando #Recomeço'
    ]
  },
  'Família': {
    inicio: [
      'A família é projeto de Deus.',
      'Deus abençoa as famílias.',
      'Família é presente divino.',
      'O amor une a família.',
      'Família é base da sociedade.',
      'Deus restaura famílias.',
      'Família é herança do Senhor.',
      'O lar é lugar de bênção.',
      'Família é plano de Deus.',
      'Unidos em Cristo somos mais fortes.'
    ],
    meio: [
      'O amor fortalece os laços familiares.',
      'Deus cuida de cada família.',
      'A oração transforma famílias.',
      'O perdão restaura relacionamentos.',
      'A graça renova a família.',
      'Cristo no centro da família.',
      'O amor vence as diferenças.',
      'A fé une a família.',
      'Deus cura relacionamentos.',
      'A família cresce em Cristo.'
    ],
    fim: [
      'Confie no cuidado de Deus.',
      'Sua família é preciosa.',
      'Deus está com sua família.',
      'O amor tudo suporta.',
      'Permita Deus agir.',
      'Sua família tem propósito.',
      'Deus restaura tudo.',
      'O amor nunca falha.',
      'Confie no tempo de Deus.',
      'Sua família é especial.'
    ],
    cta: [
      '❤️ Como você cultiva amor em família?',
      '🙏 Que tradição sua família tem?',
      '✨ Como vocês crescem juntos?',
      '💫 Que momento marcou sua família?',
      '🌟 Como vocês superam desafios?',
      '💭 Que valor você transmite?',
      '💝 Como expressam amor?',
      '🎯 Que legado você deixa?',
      '✨ Como fortalecem a união?',
      '🌈 Que bênção sua família recebeu?'
    ],
    hashtags: [
      '#Família #FamíliaEmCristo #AmorFamiliar',
      '#BênçãoFamiliar #FamíliaAbençoada #União',
      '#FamíliaEmDeus #AmorEmFamília #Relacionamentos',
      '#FamíliaRestaurada #VidaEmFamília #DeusNaFamília',
      '#FamíliaCristã #LarAbençoado #UniãoFamiliar'
    ]
  },
  'Identidade': {
    inicio: [
      'Você é uma obra-prima de Deus, criado(a) com propósito.',
      'Sua identidade em Cristo é inabalável.',
      'Antes mesmo de você nascer, Deus já te conhecia.',
      'Você é mais precioso(a) do que imagina.',
      'Sua verdadeira identidade está em Cristo.',
      'Você foi criado(a) à imagem de Deus.',
      'Sua identidade não depende do que fazem.',
      'Em Cristo, você é completo(a).',
      'Você tem valor infinito para Deus.',
      'Sua identidade é fundamentada em Cristo.',
      'Você é filho(a) amado(a) do Rei.',
      'Sua identidade é eterna em Cristo.',
      'Deus te fez único(a) e especial.',
      'Você carrega a marca do Criador.',
      'Sua identidade reflete a glória de Deus.'
    ],
    meio: [
      'O que Deus diz sobre você é mais importante que as críticas.',
      'Suas cicatrizes contam uma história de superação.',
      'Em Cristo, você é uma nova criatura.',
      'Deus não comete erros, você é especial.',
      'Sua identidade não está no que você faz, mas em quem você é.',
      'As opiniões dos outros não definem você.',
      'Deus te vê com olhos de amor.',
      'Sua identidade está segura em Cristo.',
      'O passado não define seu futuro.',
      'Em Cristo, você é transformado(a).',
      'Sua identidade é selada pelo Espírito.',
      'O amor de Deus define quem você é.',
      'Você tem um propósito único.',
      'Sua identidade é imutável em Cristo.',
      'Deus te escolheu antes da fundação do mundo.'
    ],
    fim: [
      'Aceite quem você é em Cristo.',
      'Você é amado(a) incondicionalmente por Deus.',
      'Sua identidade em Cristo é sua maior força.',
      'Permita que Deus revele quem você realmente é.',
      'Você é obra-prima do Criador.',
      'Viva sua verdadeira identidade.',
      'Celebre quem Deus te fez ser.',
      'Sua identidade é preciosa.',
      'Em Cristo, você é completo(a).',
      'Permita-se ser quem Deus te criou.',
      'Sua identidade é sua herança eterna.',
      'Viva na liberdade de sua identidade.',
      'Você é um milagre de Deus.',
      'Sua identidade é sua maior força.',
      'Descanse em quem você é em Cristo.'
    ],
    cta: [
      '🌟 Como você descobriu sua identidade em Cristo?',
      '💭 O que Deus diz sobre você?',
      '❤️ Compartilhe essa verdade com alguém que precisa ouvir',
      '✨ Você já se vê como Deus te vê?',
      '🙏 Vamos declarar juntos nossa identidade em Cristo?',
      '💫 Como você vive sua identidade?',
      '🌈 Que verdade te libertou?',
      '💝 O que te faz único(a)?',
      '🎯 Como Deus mudou sua identidade?',
      '✨ Que mentira você precisou vencer?',
      '💫 Que versículo fortalece sua identidade?',
      '🙌 Como você celebra quem é em Cristo?',
      '❤️ Que verdade transformou sua identidade?',
      '🌟 Como você expressa sua identidade?',
      '💭 Que história marca sua nova identidade?'
    ],
    hashtags: [
      '#Identidade #IdentidadeEmCristo #FilhoDeDeusÉ',
      '#NovaIdentidade #QuemSouEmCristo #Propósito',
      '#IdentidadeCristã #AutoEstima #ValorEmDeus',
      '#IdentidadeRestaurada #AutoImagem #DeusTeAma',
      '#IdentidadeVerdadeira #RenovaçãoEmCristo #Transformação'
    ]
  },
  'Santidade': {
    inicio: [
      'A santidade é um chamado para todos nós.',
      'Deus nos chama para sermos santos.',
      'Santidade é reflexo do caráter de Deus.',
      'Viver em santidade é um privilégio.',
      'A santidade nos aproxima de Deus.',
      'Santidade é viver separado para Deus.',
      'O Espírito Santo nos guia em santidade.',
      'Santidade é um processo diário.',
      'Deus nos capacita a viver em santidade.',
      'A santidade transforma nossa vida.',
      'Santidade é reflexo do amor de Deus.',
      'O caminho da santidade é libertador.',
      'Santidade é viver para agradar a Deus.',
      'A busca pela santidade nos purifica.',
      'Santidade é marca do povo de Deus.'
    ],
    meio: [
      'A santidade começa no coração.',
      'Cada escolha nos aproxima ou afasta da santidade.',
      'A Palavra de Deus nos guia em santidade.',
      'Santidade é viver para agradar a Deus.',
      'O Espírito nos ajuda a viver em santidade.',
      'Santidade é um estilo de vida.',
      'Nossas escolhas refletem nossa santidade.',
      'A graça nos conduz à santidade.',
      'Santidade é transformação diária.',
      'O amor de Deus nos leva à santidade.',
      'A santidade nos distingue do mundo.',
      'Cada passo na santidade nos transforma.',
      'A santidade purifica nosso coração.',
      'Viver em santidade é nossa resposta ao amor.',
      'A santidade nos aproxima do coração de Deus.'
    ],
    fim: [
      'Escolha viver em santidade hoje.',
      'Permita que Deus transforme sua vida.',
      'A santidade vale a pena.',
      'Viva para glorificar a Deus.',
      'Seja luz no mundo.',
      'Deixe sua vida refletir Cristo.',
      'Santidade é liberdade.',
      'Viva para honrar a Deus.',
      'Sua vida pode inspirar outros.',
      'Busque a santidade todos os dias.',
      'A santidade é nossa maior conquista.',
      'Viva para refletir a glória de Deus.',
      'Santidade é o caminho da vitória.',
      'Permita que Deus te santifique.',
      'Sua vida santa impacta o mundo.'
    ],
    cta: [
      '🙏 Como você busca a santidade?',
      '✨ Que escolhas te aproximam de Deus?',
      '💫 Como você mantém seu foco em Deus?',
      '❤️ Que hábitos fortalecem sua fé?',
      '🌟 Como você resiste às tentações?',
      '💭 Que versículo te inspira à santidade?',
      '🎯 Como você cultiva santidade?',
      '💝 Que mudanças Deus fez em você?',
      '✨ Como você vive para Deus?',
      '🙌 Que vitórias Deus te deu?',
      '💫 Como você pratica a santidade?',
      '🌟 Que escolha santa você fez hoje?',
      '❤️ Como Deus tem te santificado?',
      '💭 Que área Deus está purificando?',
      '✨ Como você busca ser mais santo(a)?'
    ],
    hashtags: [
      '#Santidade #VidaSanta #SantidadeEmCristo',
      '#VidaTransformada #SantoPraDeusÉ #Consagração',
      '#VidaEmCristo #Pureza #TransformaçãoEmDeus',
      '#SantidadeDiária #VidaConsagrada #DeusÉSanto',
      '#VidaSantificada #PurezaDeCoração #Consagrado'
    ]
  },
  'Propósito': {
    inicio: [
      'Você foi criado(a) com um propósito único.',
      'Deus tem um plano especial para você.',
      'Seu propósito está ligado ao Reino.',
      'Você tem um chamado divino.',
      'Deus planejou sua vida com amor.',
      'Seu propósito é maior que você.',
      'Você foi escolhido(a) por Deus.',
      'Seu propósito está em Cristo.',
      'Deus te criou para Sua glória.',
      'Você tem uma missão única.',
      'Seu propósito é parte do plano divino.',
      'Deus te desenhou com propósito.',
      'Você nasceu para um tempo como este.',
      'Seu propósito impacta gerações.',
      'Deus te capacita para Seu propósito.'
    ],
    meio: [
      'Cada passo te aproxima do seu propósito.',
      'Deus revela Seu propósito no tempo certo.',
      'Seu propósito impacta vidas.',
      'Confie no plano de Deus.',
      'Seu propósito está se cumprindo.',
      'Deus guia seus passos.',
      'Você foi feito(a) para mais.',
      'Seu propósito traz vida.',
      'Deus usa todas as coisas.',
      'Seu propósito é eterno.',
      'O propósito de Deus é perfeito.',
      'Cada experiência tem propósito.',
      'Seu propósito transforma vidas.',
      'Deus prepara seu caminho.',
      'Seu propósito revela Sua glória.'
    ],
    fim: [
      'Viva seu propósito hoje.',
      'Confie no plano perfeito.',
      'Seu propósito está se revelando.',
      'Permita Deus te usar.',
      'Você nasceu para isso.',
      'Seu propósito transforma vidas.',
      'Deus está te guiando.',
      'Viva para Sua glória.',
      'Seu propósito é único.',
      'Confie no processo.',
      'Seu propósito está se cumprindo.',
      'Deus honra quem O busca.',
      'Seu propósito traz vida.',
      'Continue seguindo em frente.',
      'Seu propósito impacta o mundo.'
    ],
    cta: [
      '🎯 Como você descobriu seu propósito?',
      '✨ Que sonhos Deus colocou em seu coração?',
      '💫 Como você tem vivido seu chamado?',
      '❤️ Que área Deus está te usando?',
      '🌟 Como você impacta vidas?',
      '💭 Que dons você tem usado?',
      '🙏 Como Deus te guia?',
      '💝 Que portas Deus abriu?',
      '✨ Como você serve ao Reino?',
      '🌈 Que história Deus está escrevendo?',
      '💫 Que sonho Deus está realizando?',
      '🙌 Como você vive seu propósito?',
      '❤️ Que marca você quer deixar?',
      '🌟 Como Deus tem te surpreendido?',
      '💭 Que legado você está construindo?'
    ],
    hashtags: [
      '#Propósito #PropósitoEmDeus #ChamadoDivino',
      '#VidaComPropósito #PlanoDeDeus #Missão',
      '#PropósitoEterno #ChamadoÚnico #VidaSignificativa',
      '#DescubraSeuPropósito #VocaçãoDivina #Destino',
      '#PropósitoEmCristo #ChamadoDeDeus #MissãoDivina'
    ]
  },
  'Amor de Deus': {
    inicio: [
      'O amor de Deus é incondicional e eterno.',
      'Nada pode nos separar do amor de Deus.',
      'O amor de Deus nos alcança onde estamos.',
      'Mesmo quando falhamos, Deus nos ama.',
      'O amor de Deus transforma vidas.',
      'O amor de Deus é nossa força.',
      'Seu amor nos sustenta sempre.',
      'O amor de Deus é imensurável.',
      'Seu amor nos aceita como somos.',
      'O amor de Deus nunca falha.'
    ],
    meio: [
      'Seu amor nos aceita como somos.',
      'O amor de Deus cura todas as feridas.',
      'Em Seu amor, encontramos força para continuar.',
      'O amor de Deus nunca falha.',
      'Seu amor nos liberta do medo.',
      'O amor de Deus restaura vidas.',
      'Seu amor nos dá esperança.',
      'O amor de Deus nos renova.',
      'Seu amor nos fortalece.',
      'O amor de Deus nos guia.'
    ],
    fim: [
      'Permita-se ser amado(a) por Deus.',
      'O amor dEle é maior que nossos erros.',
      'Descanse no amor incondicional de Deus.',
      'Seu amor nos transforma por dentro.',
      'Nada pode mudar o amor de Deus por você.',
      'O amor de Deus é nossa certeza.',
      'Seu amor nos sustenta.',
      'O amor de Deus é eterno.',
      'Seu amor nos completa.',
      'O amor de Deus é perfeito.'
    ],
    cta: [
      '❤️ Como você experimenta o amor de Deus?',
      '🙏 Que momento você sentiu mais o amor de Deus?',
      '✨ Como o amor de Deus mudou sua vida?',
      '💫 Que história de amor você tem com Deus?',
      '🌟 Como você compartilha o amor de Deus?',
      '💭 Que versículo sobre o amor de Deus te toca?',
      '💝 Como você demonstra amor a Deus?',
      '🎯 Que área o amor de Deus está curando?',
      '✨ Como você cresceu no amor de Deus?',
      '🌈 Que testemunho do amor de Deus você tem?'
    ],
    hashtags: [
      '#AmorDeDeus #DeusÉAmor #AmorIncondicional',
      '#AmorEterno #AmorDivino #GraçaDeDeus',
      '#AmorInfinito #DeusTeAma #AmorPerfeito',
      '#AmorQueTransforma #AmorVerdadeiro #DeusÉFiel',
      '#AmorInabalável #AmorDoPai #GraçaInfinita'
    ]
  },
  'Cura': {
    inicio: [
      'Deus é o médico dos médicos.',
      'Em Cristo há cura e restauração.',
      'O poder de Deus traz cura.',
      'Jesus é o mesmo ontem e hoje.',
      'A cura vem do Senhor.',
      'Deus pode curar todas as feridas.',
      'Em Suas feridas fomos curados.',
      'O toque de Deus traz cura.',
      'Cristo é nossa cura completa.',
      'Deus restaura e cura.',
      'A cura divina é para hoje.',
      'Deus é especialista em curar.',
      'O poder de cura está disponível.',
      'Jesus ainda cura hoje.',
      'A cura começa na presença de Deus.'
    ],
    meio: [
      'A cura começa no interior.',
      'Deus conhece sua dor.',
      'O poder de Deus é ilimitado.',
      'A fé move o coração de Deus.',
      'Sua cura está a caminho.',
      'Confie no poder restaurador.',
      'Deus está trabalhando agora.',
      'A cura é um processo divino.',
      'Permita Deus te curar.',
      'O amor de Deus cura.',
      'A cura acontece no tempo certo.',
      'Deus está restaurando tudo.',
      'Sua fé ativa a cura.',
      'O poder de Deus é maior.',
      'A cura vem pela fé.'
    ],
    fim: [
      'Receba sua cura hoje.',
      'Creia na cura divina.',
      'Deus pode te curar.',
      'Sua cura está chegando.',
      'Confie no poder de Deus.',
      'A cura está disponível.',
      'Permita-se ser curado.',
      'Deus quer te curar.',
      'Sua fé traz cura.',
      'A cura é para hoje.',
      'Seu milagre está a caminho.',
      'A cura é sua herança.',
      'Deus é fiel para curar.',
      'Receba sua restauração.',
      'A cura manifesta Sua glória.'
    ],
    cta: [
      '🙏 Como Deus tem te curado?',
      '✨ Que área precisa de cura?',
      '💫 Como você tem buscado cura?',
      '❤️ Que testemunho de cura você tem?',
      '🌟 Como a fé te ajuda na cura?',
      '💭 Que promessa te dá esperança?',
      '💝 Como Deus tem te restaurado?',
      '🎯 Que cura você espera?',
      '✨ Como você mantém sua fé?',
      '🌈 Que milagre você já viu?',
      '💫 Como você tem esperado em Deus?',
      '🙌 Que área Deus já curou?',
      '❤️ Como você mantém sua esperança?',
      '🌟 Que versículo de cura te fortalece?',
      '💭 Como você tem experimentado a cura?'
    ],
    hashtags: [
      '#Cura #CuraDivina #CuraEmCristo',
      '#RestauracaoEmDeus #CuraERestauracao #Milagre',
      '#PoderDeCura #CuraInterior #RestauracaoTotal',
      '#CuraPossivel #DeusEFiel #CuraELibertacao',
      '#CuraESaude #RestauracaoDivina #MilagreDeCura'
    ]
  },
  'Libertação': {
    inicio: [
      'Em Cristo somos livres.',
      'A verdade liberta.',
      'Onde está o Espírito do Senhor, aí há liberdade.',
      'Jesus quebra todas as cadeias.',
      'A libertação é um processo.',
      'Deus quer te libertar.',
      'Liberdade verdadeira vem de Cristo.',
      'Você foi criado para ser livre.',
      'A libertação começa na mente.',
      'Cristo nos faz verdadeiramente livres.',
      'A libertação é um presente divino.',
      'Deus quebra toda prisão.',
      'Liberdade plena em Cristo.',
      'A verdade te faz livre.',
      'Sua libertação está em Cristo.'
    ],
    meio: [
      'A libertação é um presente de Deus.',
      'Permaneça firme na liberdade.',
      'Deus quebra toda prisão.',
      'A libertação traz cura interior.',
      'Cristo liberta completamente.',
      'Viva em liberdade.',
      'A libertação é para todos.',
      'Deus restaura vidas.',
      'A libertação traz paz.',
      'Seja livre em Cristo.',
      'A libertação é progressiva.',
      'Deus remove toda prisão.',
      'Liberdade que transforma.',
      'O poder que liberta.',
      'Cristo liberta totalmente.'
    ],
    fim: [
      'Mantenha-se firme na liberdade.',
      'Viva como filho livre.',
      'Sua libertação inspira outros.',
      'A liberdade em Cristo é eterna.',
      'Celebre sua libertação.',
      'Ajude outros a serem livres.',
      'Testemunhe sua libertação.',
      'A liberdade é sua herança.',
      'Viva em plena liberdade.',
      'Seja um agente de libertação.',
      'Sua libertação é completa.',
      'Permaneça na liberdade.',
      'A libertação traz vida.',
      'Caminhe em liberdade.',
      'Sua história liberta outros.'
    ],
    cta: [
      '🔓 Como você experimenta a liberdade em Cristo?',
      '❤️ Qual área você já foi liberto?',
      '✨ Compartilhe seu testemunho de libertação',
      '💫 Vamos orar por libertação?',
      '🙏 Como você mantém sua liberdade?',
      '💭 Que área precisa de libertação?',
      '🌟 Como Deus te libertou?',
      '💪 Como você ajuda outros a serem livres?',
      '📖 Qual versículo sobre libertação te marca?',
      '🙌 Vamos celebrar a libertação!',
      '💫 Que mudança a libertação trouxe?',
      '🌟 Como você vive sua liberdade?',
      '❤️ Que área Deus está libertando?',
      '💭 Como você mantém sua libertação?',
      '✨ Que vitória você já conquistou?'
    ],
    hashtags: [
      '#Libertacao #LibertosEmCristo #Liberdade',
      '#PoderDeDeus #LibertacaoTotal #Vitoria',
      '#LibertosParaAdorar #NovaVida #Transformacao',
      '#LibertacaoDivina #DeusEFiel #Restauracao',
      '#LiberdadeEmCristo #VidaLivre #LibertosParaViver'
    ]
  },
  'Gratidão': {
    inicio: [
      'A gratidão transforma o pouco em muito.',
      'Um coração grato atrai bênçãos.',
      'A gratidão é uma forma poderosa de oração.',
      'Ser grato muda nossa perspectiva.',
      'A gratidão nos aproxima de Deus.',
      'Mesmo nas dificuldades, há motivos para agradecer.',
      'A gratidão é um ato de fé.',
      'Um coração agradecido vê milagres.',
      'A gratidão abre portas no céu.',
      'Agradecer é reconhecer o cuidado de Deus.',
      'A gratidão multiplica bênçãos.',
      'Ser grato é um estilo de vida.',
      'A gratidão transforma realidades.',
      'Um coração grato atrai favor.',
      'A gratidão é uma chave espiritual.'
    ],
    meio: [
      'Cada novo dia é um presente de Deus.',
      'A gratidão nos ensina a ver o extraordinário no ordinário.',
      'Quando agradecemos, multiplicamos as bênçãos.',
      'A gratidão transforma nossa atitude.',
      'Ser grato nos faz mais felizes.',
      'A gratidão é um antídoto para a ansiedade.',
      'Agradecer nos ajuda a ver a bondade de Deus.',
      'Um coração grato está sempre em paz.',
      'A gratidão nos mantém humildes.',
      'Agradecer é um ato de adoração.',
      'A gratidão muda nossa perspectiva.',
      'Ser grato nos aproxima de Deus.',
      'A gratidão é uma expressão de fé.',
      'Agradecer fortalece a alma.',
      'A gratidão traz contentamento.'
    ],
    fim: [
      'Comece e termine seu dia com gratidão.',
      'A gratidão muda tudo.',
      'Seja grato pelo que você tem hoje.',
      'A gratidão atrai mais bênçãos.',
      'Um coração grato é um coração feliz.',
      'A gratidão nos faz crescer espiritualmente.',
      'Agradeça antes de ver a resposta.',
      'A gratidão é uma escolha diária.',
      'Ser grato transforma vidas.',
      'A gratidão é uma forma de amor.',
      'Cultive um coração agradecido.',
      'A gratidão é uma força poderosa.',
      'Agradecer é reconhecer a Deus.',
      'A gratidão traz paz interior.',
      'Seja grato em todo tempo.'
    ],
    cta: [
      '🙏 O que te faz ser grato hoje?',
      '✨ Como você expressa gratidão?',
      '💫 Que bênção te faz agradecer?',
      '❤️ Como a gratidão mudou sua vida?',
      '🌟 Por que você é grato a Deus?',
      '💭 Que motivo de gratidão você tem?',
      '💝 Como você cultiva gratidão?',
      '🎯 Que bênção te surpreendeu?',
      '✨ Como você agradece a Deus?',
      '🌈 Que milagre te faz agradecer?',
      '💫 Como você pratica gratidão?',
      '🙌 Que história de gratidão você tem?',
      '❤️ Como a gratidão te transforma?',
      '🌟 Que presente de Deus te faz grato?',
      '💭 Como você mantém um coração grato?'
    ],
    hashtags: [
      '#Gratidao #CoracaoGrato #GratidaoADeus',
      '#SerGrato #GratidaoDiaria #Agradecer',
      '#GratidaoSempre #CoracaoAgradecido #Bencaos',
      '#GratidaoEFe #DeusEFiel #Reconhecimento',
      '#GratidaoEAmor #VidaGrata #GratidaoConstante'
    ]
  },
  'Adoração': {
    inicio: [
      'A adoração vai além da música.',
      'Adorar é entregar tudo a Deus.',
      'Na adoração, encontramos a presença de Deus.',
      'Adorar é reconhecer quem Deus é.',
      'A verdadeira adoração vem do coração.',
      'Adorar em espírito e em verdade.',
      'A adoração quebra cadeias.',
      'Na adoração, somos transformados.',
      'Adorar é nossa resposta ao amor de Deus.',
      'A adoração muda atmosferas.',
      'A adoração é um estilo de vida.',
      'Adorar é se render totalmente.',
      'Na adoração, há poder.',
      'A adoração toca o coração de Deus.',
      'Adorar é viver para Sua glória.'
    ],
    meio: [
      'Quando adoramos, o céu toca a terra.',
      'A adoração nos conecta ao coração de Deus.',
      'Na adoração, encontramos direção.',
      'Adorar é render-se completamente.',
      'A adoração traz cura e libertação.',
      'Quando adoramos, batalhas são vencidas.',
      'A adoração nos leva à intimidade com Deus.',
      'Na adoração, milagres acontecem.',
      'Adorar é declarar a grandeza de Deus.',
      'A adoração transforma vidas.',
      'A adoração rompe barreiras.',
      'Na adoração, há breakthrough.',
      'Adorar é expressar gratidão.',
      'A adoração move o coração de Deus.',
      'Quando adoramos, Deus age.'
    ],
    fim: [
      'Seja um adorador em espírito e em verdade.',
      'Faça da sua vida um ato de adoração.',
      'A adoração é um estilo de vida.',
      'Adore com todo seu coração.',
      'Na adoração, encontramos paz.',
      'Que sua vida seja uma adoração constante.',
      'A adoração nos aproxima de Deus.',
      'Adore em todos os momentos.',
      'A adoração é nossa arma mais poderosa.',
      'Viva para adorar.',
      'A adoração transforma tudo.',
      'Seja um adorador verdadeiro.',
      'Na adoração, há vitória.',
      'Adore em todo tempo.',
      'A adoração é nossa força.'
    ],
    cta: [
      '🙌 Como você expressa sua adoração a Deus?',
      '❤️ Qual música de adoração toca seu coração?',
      '✨ Compartilhe seu momento mais especial de adoração',
      '💫 Vamos adorar juntos?',
      '🎵 Que canção de adoração te marcou?',
      '🙏 Como você adora além da música?',
      '💭 O que a adoração significa para você?',
      '📖 Qual passagem bíblica te inspira a adorar?',
      '💝 Como você cultiva um coração adorador?',
      '👉 Marque um adorador que te inspira',
      '💫 Como a adoração mudou sua vida?',
      '🙌 Que momento de adoração te marcou?',
      '❤️ Como você mantém um espírito adorador?',
      '🌟 Que experiência de adoração te transformou?',
      '💭 Como você adora no dia a dia?'
    ],
    hashtags: [
      '#Adoracao #AdoracaoVerdadeira #AdorarADeus',
      '#Adorador #ViverParaAdorar #Louvor',
      '#AdoracaoELouvor #CoracaoAdorador #Adorar',
      '#AdoracaoEmEspirito #VidaDeAdoracao #DeusEFiel',
      '#AdoracaoSincera #MomentoDeAdoracao #AdorarSempre'
    ]
  },
  'Paz': {
    inicio: [
      'A paz de Deus excede todo entendimento.',
      'Em meio ao caos, podemos encontrar paz.',
      'Jesus é o Príncipe da Paz.',
      'A verdadeira paz vem do alto.',
      'Paz não é ausência de conflito, é presença de Deus.',
      'Na tempestade, podemos ter paz.',
      'A paz de Cristo guarda nosso coração.',
      'Paz é um fruto do Espírito.',
      'Encontre paz na presença de Deus.',
      'A paz divina transcende as circunstâncias.',
      'A paz de Deus é sobrenatural.',
      'Em Cristo, temos paz perfeita.',
      'A paz é um dom divino.',
      'Sua paz nos fortalece.',
      'A paz de Deus é constante.'
    ],
    meio: [
      'Quando confiamos em Deus, a paz reina.',
      'A paz de Deus é nossa fortaleza.',
      'Em Sua presença, há plenitude de paz.',
      'A paz verdadeira vem do relacionamento com Deus.',
      'Mesmo na tribulação, podemos ter paz.',
      'A paz de Deus guarda nossa mente.',
      'Jesus nos dá uma paz diferente.',
      'A paz é um presente divino.',
      'Na paz de Deus, encontramos descanso.',
      'Sua paz nos sustenta em todo tempo.',
      'A paz de Deus renova nossas forças.',
      'Em Sua paz, há segurança.',
      'A paz divina nos equilibra.',
      'Sua paz traz clareza.',
      'A paz de Deus nos guia.'
    ],
    fim: [
      'Permita que a paz de Deus reine em seu coração.',
      'Seja um instrumento de paz.',
      'Cultive a paz em sua vida.',
      'Deixe a paz de Cristo fluir.',
      'A paz de Deus está disponível para você.',
      'Escolha viver em paz.',
      'Que a paz de Deus te envolva.',
      'Seja guardado na perfeita paz.',
      'Mantenha seu coração em paz.',
      'A paz é sua herança em Cristo.',
      'Viva na paz do Senhor.',
      'Sua paz nos completa.',
      'Descanse em Sua paz.',
      'A paz te guarda sempre.',
      'Permaneça em Sua paz.'
    ],
    cta: [
      '🕊️ Como você encontra paz em meio ao caos?',
      '❤️ O que te traz paz verdadeira?',
      '✨ Compartilhe um momento de paz com Deus',
      '💫 Vamos declarar paz sobre sua vida?',
      '🙏 Precisa de paz hoje?',
      '💭 Como você mantém a paz em tempos difíceis?',
      '🌟 Que versículo sobre paz mais te conforta?',
      '💖 Marque alguém que precisa de paz',
      '🙌 Vamos orar por paz juntos?',
      '📖 Qual sua história de paz com Deus?',
      '💫 Como você cultiva a paz?',
      '🙌 Que momento de paz te marcou?',
      '❤️ Como a paz de Deus te transforma?',
      '🌟 Que experiência de paz te fortaleceu?',
      '💭 Como você encontra paz diariamente?'
    ],
    hashtags: [
      '#Paz #PazDeDeus #PazInterior',
      '#PazDivina #PazPerfeita #PazEmCristo',
      '#PazVerdadeira #PazEspiritual #Tranquilidade',
      '#PazESerenidade #PazNoSenhor #PazEAmor',
      '#PazEFe #PazEterna #PazQueSobrepuja'
    ]
  },
  'Perseverança': {
    inicio: [
      'A perseverança produz caráter.',
      'Continue firme, a vitória está próxima.',
      'Não desista no meio do processo.',
      'A perseverança é marca do verdadeiro cristão.',
      'Deus honra quem persevera.',
      'Na perseverança, encontramos força.',
      'Cada passo é uma vitória.',
      'Perseverar é confiar no tempo de Deus.',
      'A perseverança revela nossa fé.',
      'Continue avançando, não pare agora.',
      'A perseverança forja campeões.',
      'Sua persistência será recompensada.',
      'Não desista dos seus sonhos.',
      'A perseverança vence batalhas.',
      'Continue firme na caminhada.'
    ],
    meio: [
      'Deus fortalece quem persevera.',
      'A perseverança molda nosso caráter.',
      'Em Cristo, temos força para continuar.',
      'Cada obstáculo é uma oportunidade de crescer.',
      'A perseverança traz recompensa.',
      'Não desista dos seus sonhos em Deus.',
      'A jornada forma o guerreiro.',
      'Perseverar é confiar nas promessas.',
      'Deus vê seu esforço e dedicação.',
      'Continue firme em sua caminhada.',
      'A perseverança traz maturidade.',
      'Cada desafio te fortalece.',
      'Sua persistência fará história.',
      'A perseverança revela propósito.',
      'Continue avançando em fé.'
    ],
    fim: [
      'Sua perseverança será recompensada.',
      'Mantenha-se firme até o fim.',
      'A vitória pertence a quem persevera.',
      'Não desista, Deus está com você.',
      'Seu testemunho inspirará outros.',
      'A perseverança produz esperança.',
      'Continue lutando a boa batalha.',
      'Sua história ainda não acabou.',
      'Persevere em oração e fé.',
      'O melhor está por vir.',
      'Sua persistência vale a pena.',
      'Continue firme no propósito.',
      'A vitória vem pela perseverança.',
      'Não pare de acreditar.',
      'Sua história inspirará gerações.'
    ],
    cta: [
      '💪 O que te motiva a perseverar?',
      '🙏 Como você mantém a força na caminhada?',
      '✨ Compartilhe sua história de perseverança',
      '💫 Vamos declarar vitória em sua vida?',
      '❤️ Marque alguém que é exemplo de perseverança',
      '🌟 Qual batalha você está vencendo hoje?',
      '💭 Como você supera os obstáculos?',
      '🙌 Vamos orar por sua perseverança?',
      '📖 Que versículo te fortalece a continuar?',
      '💪 Continue firme, guerreiro(a)!',
      '💫 Como você mantém a perseverança?',
      '🙌 Que vitória sua perseverança já trouxe?',
      '❤️ Como você persevera na fé?',
      '🌟 Que testemunho de perseverança você tem?',
      '💭 Como você vence o desânimo?'
    ],
    hashtags: [
      '#Perseveranca #NaoDesista #ForcaEFe',
      '#Persistencia #VitoriaEmCristo #Superacao',
      '#PerseverarSempre #FeInabalavel #Determinacao',
      '#PerseverancaEFe #VencerEmCristo #NaoPare',
      '#PerseverancaDiaria #GuerreiroDeFe #Conquista'
    ]
  },
  'Sabedoria': {
    inicio: [
      'A verdadeira sabedoria vem de Deus.',
      'O temor do Senhor é o princípio da sabedoria.',
      'A sabedoria divina nos guia em cada decisão.',
      'Busque a sabedoria mais que ouro.',
      'A sabedoria de Deus supera a humana.',
      'Em Cristo estão todos os tesouros da sabedoria.',
      'A sabedoria celestial é pura e pacífica.',
      'Peça sabedoria a Deus com fé.',
      'A sabedoria nos ajuda a viver melhor.',
      'Deus dá sabedoria a quem pede.',
      'A sabedoria é um dom precioso.',
      'Busque a sabedoria do alto.',
      'A sabedoria ilumina o caminho.',
      'Em Deus está toda sabedoria.',
      'A sabedoria traz discernimento.'
    ],
    meio: [
      'A sabedoria nos ensina a fazer escolhas certas.',
      'Com sabedoria, construímos um futuro melhor.',
      'A Palavra de Deus é fonte de sabedoria.',
      'A sabedoria nos protege de erros.',
      'Deus quer nos dar sabedoria para viver.',
      'A sabedoria nos faz prosperar.',
      'Com sabedoria, tomamos melhores decisões.',
      'A sabedoria divina nunca falha.',
      'Busque sabedoria em cada situação.',
      'A sabedoria nos traz discernimento.',
      'A sabedoria nos guia sempre.',
      'Com sabedoria, vencemos desafios.',
      'A sabedoria traz equilíbrio.',
      'Deus nos ensina com sabedoria.',
      'A sabedoria ilumina decisões.'
    ],
    fim: [
      'Peça sabedoria a Deus todos os dias.',
      'A sabedoria é um presente divino.',
      'Use a sabedoria para glorificar a Deus.',
      'Compartilhe a sabedoria que recebeu.',
      'A sabedoria transforma nossa vida.',
      'Seja um canal da sabedoria de Deus.',
      'A sabedoria nos faz crescer.',
      'Aplique a sabedoria em tudo.',
      'A sabedoria nos aproxima de Deus.',
      'Viva com a sabedoria do alto.',
      'A sabedoria traz vitória.',
      'Cultive a sabedoria divina.',
      'A sabedoria é seu tesouro.',
      'Cresça em sabedoria sempre.',
      'A sabedoria guia seus passos.'
    ],
    cta: [
      '🤔 Como você busca sabedoria diariamente?',
      '📖 Qual versículo sobre sabedoria mais te marca?',
      '💭 Compartilhe uma decisão sábia que você tomou',
      '🙏 Vamos pedir sabedoria juntos?',
      '✨ Como a sabedoria de Deus te guiou?',
      '💫 Que conselho sábio você recebeu?',
      '❤️ Marque alguém que é exemplo de sabedoria',
      '🌟 Como você aplica a sabedoria na prática?',
      '📝 Que lição de sabedoria você aprendeu hoje?',
      '🎯 Que área da sua vida precisa de mais sabedoria?',
      '💫 Como você cultiva sabedoria?',
      '🙌 Que decisão sábia te abençoou?',
      '❤️ Como a sabedoria te transforma?',
      '🌟 Que experiência te trouxe sabedoria?',
      '💭 Como você busca sabedoria em Deus?'
    ],
    hashtags: [
      '#Sabedoria #SabedoriaDivina #SabedoriaDeDeus',
      '#BuscandoSabedoria #SabedoriaCelestial #Discernimento',
      '#SabedoriaEFe #SabedoriaBiblica #SabedoriaPratica',
      '#SabedoriaDeVida #SabedoriaEterna #DeusESabio',
      '#SabedoriaInfinita #SabedoriaCrista #VidaSabia'
    ]
  },
  'Oração': {
    inicio: [
      'A oração muda tudo.',
      'Na oração, encontramos força.',
      'Ore sem cessar.',
      'A oração é nossa arma mais poderosa.',
      'Através da oração, nos conectamos com Deus.',
      'A oração abre portas no céu.',
      'O poder da oração é ilimitado.',
      'Na oração, há vitória.',
      'A oração transforma realidades.',
      'Ore com fé e perseverança.',
      'A oração move montanhas.',
      'Na oração, há poder.',
      'A oração é nossa conexão com Deus.',
      'Ore com expectativa.',
      'A oração é nossa força.'
    ],
    meio: [
      'Deus ouve cada oração.',
      'A oração fortalece nossa fé.',
      'Na oração, encontramos direção.',
      'A oração nos aproxima de Deus.',
      'Ore em todo tempo e lugar.',
      'A oração move o coração de Deus.',
      'Na oração, há poder.',
      'A oração muda circunstâncias.',
      'Ore com confiança.',
      'A oração é diálogo com Deus.',
      'A oração traz resposta.',
      'Na oração, há milagres.',
      'A oração transforma vidas.',
      'Ore com perseverança.',
      'A oração é nossa vitória.'
    ],
    fim: [
      'Mantenha sua vida de oração ativa.',
      'A oração é sua conexão com Deus.',
      'Nunca subestime o poder da oração.',
      'Seja constante em oração.',
      'A oração é sua força diária.',
      'Continue orando sem desanimar.',
      'A oração traz breakthrough.',
      'Ore com expectativa.',
      'A oração é sua chave de vitória.',
      'Deus responde orações.',
      'A oração é seu privilégio.',
      'Na oração, há transformação.',
      'A oração é sua força.',
      'Ore sem cessar.',
      'A oração é seu poder.'
    ],
    cta: [
      '🙏 Como está sua vida de oração?',
      '✨ Compartilhe um testemunho de oração',
      '💫 Vamos orar juntos?',
      '❤️ Qual seu momento favorito para orar?',
      '🌟 Como você mantém sua vida de oração?',
      '💭 Que pedido de oração você tem hoje?',
      '📖 Qual sua oração favorita?',
      '🙌 Como Deus respondeu suas orações?',
      '💝 Marque alguém para orar junto',
      '🎯 Que área precisa de mais oração?',
      '💫 Como você cultiva oração?',
      '🙌 Que resposta de oração você teve?',
      '❤️ Como a oração te transforma?',
      '🌟 Que experiência de oração te marcou?',
      '💭 Como você mantém sua vida de oração?'
    ],
    hashtags: [
      '#Oracao #PoderDaOracao #VidaDeOracao',
      '#OracaoEFe #OracaoPoderosoa #DeusOuve',
      '#OracaoConstante #OracaoEAdoracao #Fe',
      '#OracaoTransforma #OracaoEMilagre #Intercessao',
      '#OracaoEPoder #OracaoDiaria #VidaDeOracao'
    ]
  },
  'Missões': {
    inicio: [
      'O campo é o mundo.',
      'Ide por todo o mundo.',
      'A seara é grande, mas os trabalhadores são poucos.',
      'Cada cristão é um missionário.',
      'O evangelho precisa alcançar todas as nações.',
      'Missões é o coração de Deus.',
      'Seja luz onde você estiver.',
      'Você é chamado para missões.',
      'O mundo precisa de Jesus.',
      'Missões começa em casa.',
      'Sua vida é missão.',
      'O chamado é para todos.',
      'Missões é amor em ação.',
      'Seja um embaixador de Cristo.',
      'O mundo espera por você.'
    ],
    meio: [
      'Deus quer usar você para alcançar vidas.',
      'Cada um tem um papel nas missões.',
      'Seja um missionário onde estiver.',
      'O evangelho precisa ser pregado.',
      'Missões é amor em ação.',
      'Você pode impactar nações.',
      'Deus quer alcançar todos os povos.',
      'Seja um embaixador de Cristo.',
      'Missões é obediência a Deus.',
      'Compartilhe o amor de Jesus.',
      'Sua vida é testemunho.',
      'Missões é um estilo de vida.',
      'Alcance vidas para Cristo.',
      'Seja sal e luz.',
      'O mundo precisa de esperança.'
    ],
    fim: [
      'Faça sua parte na Grande Comissão.',
      'Seja um missionário todos os dias.',
      'O mundo precisa do seu testemunho.',
      'Viva em missão constantemente.',
      'Alcance vidas para Jesus.',
      'Seja um agente de transformação.',
      'Sua vida pode impactar nações.',
      'Compartilhe o amor de Cristo.',
      'Viva o chamado missionário.',
      'Seja luz onde estiver.',
      'Sua missão é importante.',
      'O mundo precisa de você.',
      'Seja um missionário fiel.',
      'Impacte vidas para Cristo.',
      'Viva para a missão.'
    ],
    cta: [
      '🌍 Como você vive sua missão?',
      '❤️ Que área você quer impactar?',
      '✨ Compartilhe seu testemunho missionário',
      '💫 Vamos orar pelas nações?',
      '🙏 Como você tem sido missionário?',
      '💭 Que campo Deus te mostrou?',
      '🌟 Como você alcança vidas?',
      '💪 Que missão Deus te deu?',
      '📖 Qual versículo missionário te inspira?',
      '🌍 Ore pelas nações hoje!',
      '💫 Como você impacta vidas?',
      '🙌 Que testemunho missionário você tem?',
      '❤️ Como você vive em missão?',
      '🌟 Que experiência missionária te marcou?',
      '💭 Como você compartilha Jesus?'
    ],
    hashtags: [
      '#Missoes #MissoesEVida #ChamadoMissionario',
      '#VidaEmMissao #MissoesUrbanas #AlcanceVidas',
      '#MissoesMundiais #ImpactoMissionario #Evangelismo',
      '#MissoesEFe #VidaMissionaria #CompartilheJesus',
      '#MissoesEAmor #SerMissionario #AlcanceNacoes'
    ]
  },
  'Evangelismo': {
    inicio: [
      'O evangelho é poder de Deus para salvação.',
      'Compartilhe Jesus com amor.',
      'Cada encontro é uma oportunidade.',
      'Seja luz no mundo.',
      'O evangelho transforma vidas.',
      'Jesus é a resposta.',
      'Compartilhe sua história com Cristo.',
      'O mundo precisa de esperança.',
      'Seja um mensageiro do amor.',
      'O evangelho é para todos.',
      'Sua vida é testemunho.',
      'O amor abre portas.',
      'Evangelizar é amar.',
      'Seja um canal de bênção.',
      'O evangelho é vida.'
    ],
    meio: [
      'Seu testemunho pode mudar vidas.',
      'O amor de Deus alcança a todos.',
      'Compartilhe a verdade com graça.',
      'Seja um exemplo de Cristo.',
      'O evangelho é poder transformador.',
      'Deus quer usar sua história.',
      'Cada vida importa para Deus.',
      'Seja intencional em compartilhar.',
      'O amor abre portas.',
      'Sua vida é seu testemunho.',
      'O evangelho é poder.',
      'Compartilhe com sabedoria.',
      'Sua história inspira.',
      'O amor transforma.',
      'Seja intencional.'
    ],
    fim: [
      'Seja um evangelista do amor.',
      'Compartilhe Jesus todos os dias.',
      'Faça a diferença onde está.',
      'O evangelho muda tudo.',
      'Seja um embaixador de Cristo.',
      'Viva o evangelho na prática.',
      'Alcance um de cada vez.',
      'Sua vida pode inspirar muitos.',
      'Seja sal e luz.',
      'O amor é a maior mensagem.',
      'Sua vida é testemunho.',
      'Compartilhe com amor.',
      'O evangelho transforma.',
      'Seja um canal de bênção.',
      'Alcance vidas para Cristo.'
    ],
    cta: [
      '🌟 Como você compartilha Jesus?',
      '❤️ Qual seu testemunho favorito?',
      '✨ Compartilhe uma experiência evangelística',
      '💫 Vamos alcançar vidas juntos?',
      '🙏 Como você evangeliza no dia a dia?',
      '💭 Que estratégia você usa para evangelizar?',
      '📖 Qual versículo te motiva a evangelizar?',
      '🙌 Como Deus tem usado sua vida?',
      '💝 Marque alguém que precisa de Jesus',
      '🎯 Que área você quer impactar?',
      '💫 Como você testemunha Cristo?',
      '🙌 Que vida você quer alcançar?',
      '❤️ Como você compartilha o amor?',
      '🌟 Que experiência te marcou?',
      '💭 Como você evangeliza?'
    ],
    hashtags: [
      '#Evangelismo #CompartilhandoJesus #AlcancandoVidas',
      '#EvangelismoUrbano #TestemunhoDeFe #EvangelhoVivo',
      '#CompartilhandoAmor #EvangelismoPratico #JesusTransforma',
      '#EvangelismoEFe #AlcancandoAlmas #VidaTransformada',
      '#EvangelismoDeAmor #TestemunhoVivo #ImpactoEterno'
    ]
  },
  'Discipulado': {
    inicio: [
      'Discipulado é multiplicação.',
      'Seja um discípulo multiplicador.',
      'Invista em vidas.',
      'O discipulado transforma gerações.',
      'Aprenda para ensinar.',
      'Discipulado é relacionamento.',
      'Seja um mentor espiritual.',
      'Discipulado é amor em ação.',
      'Multiplique o que aprendeu.',
      'Discipulado é vida.',
      'Discipulado é investimento.',
      'Forme novos discípulos.',
      'Discipulado é transformação.',
      'Seja um mentor fiel.',
      'Discipulado é legado.'
    ],
    meio: [
      'Invista tempo em pessoas.',
      'O discipulado forma caráter.',
      'Compartilhe o que aprendeu.',
      'Seja um exemplo a seguir.',
      'O discipulado é intencional.',
      'Forme novos líderes.',
      'Multiplique o Reino.',
      'Discipulado é processo.',
      'Invista em relacionamentos.',
      'Seja um mentor presente.',
      'O discipulado transforma.',
      'Forme vidas para Cristo.',
      'Discipulado é dedicação.',
      'Seja um exemplo vivo.',
      'O discipulado é amor.'
    ],
    fim: [
      'Faça discípulos para Jesus.',
      'Multiplique sua vida.',
      'Deixe um legado eterno.',
      'Forme novos discípulos.',
      'Seja um discipulador fiel.',
      'Invista no Reino.',
      'Transforme vidas.',
      'Seja intencional.',
      'Multiplique a visão.',
      'Forme líderes para Deus.',
      'O discipulado vale a pena.',
      'Forme novas gerações.',
      'Discipulado é multiplicação.',
      'Seja um mentor de valor.',
      'Transforme o futuro.'
    ],
    cta: [
      '👥 Como você discipula outros?',
      '❤️ Quem te discipulou na fé?',
      '✨ Compartilhe sua experiência de discipulado',
      '💫 Vamos multiplicar juntos?',
      '🙏 Como você investe em vidas?',
      '💭 Que princípio de discipulado mais te marca?',
      '📖 Qual sua estratégia de discipulado?',
      '🙌 Como você forma novos líderes?',
      '💝 Marque alguém que te inspira',
      '🎯 Que área você quer multiplicar?',
      '💫 Como você forma discípulos?',
      '🙌 Que vida você está discipulando?',
      '❤️ Como o discipulado te transformou?',
      '🌟 Que experiência te marcou?',
      '💭 Como você multiplica a visão?'
    ],
    hashtags: [
      '#Discipulado #Multiplicacao #FormandoLideres',
      '#DiscipuladoEfetivo #Mentoria #Crescimento',
      '#DiscipuladoCristao #MultiplicandoVidas #NovosDiscipulos',
      '#DiscipuladoRelacional #FormandoVidas #Investimento',
      '#DiscipuladoIntencional #MultiplicacaoDeVidas #Legado'
    ]
  },
  'Liderança': {
    inicio: [
      'Liderar é servir.',
      'Um líder forma outros líderes.',
      'Liderança é influência.',
      'Seja um líder servo.',
      'Lidere pelo exemplo.',
      'Liderança é responsabilidade.',
      'Forme novos líderes.',
      'Liderança é visão.',
      'Seja um líder multiplicador.',
      'Liderança é caráter.',
      'Liderança é influência positiva.',
      'Lidere com propósito.',
      'Liderança é servir outros.',
      'Seja um líder inspirador.',
      'Liderança é transformação.'
    ],
    meio: [
      'Lidere com amor e graça.',
      'Um líder desenvolve pessoas.',
      'Liderança é sobre outros.',
      'Forme uma equipe forte.',
      'Lidere com integridade.',
      'Seja um mentor presente.',
      'Desenvolva outros líderes.',
      'Liderança é influência positiva.',
      'Invista em pessoas.',
      'Seja um exemplo a seguir.',
      'Liderança é multiplicação.',
      'Forme novos líderes.',
      'Lidere com sabedoria.',
      'Desenvolva talentos.',
      'Liderança é serviço.'
    ],
    fim: [
      'Deixe um legado de liderança.',
      'Forme a próxima geração.',
      'Seja um líder que serve.',
      'Multiplique sua liderança.',
      'Impacte vidas positivamente.',
      'Desenvolva novos líderes.',
      'Seja um líder de valor.',
      'Forme uma equipe vencedora.',
      'Lidere com propósito.',
      'Seja um líder que inspira.',
      'Liderança que transforma.',
      'Forme líderes servos.',
      'Lidere com excelência.',
      'Desenvolva outros.',
      'Seja um líder mentor.'
    ],
    cta: [
      '👑 Como você lidera sua equipe?',
      '❤️ Qual seu estilo de liderança?',
      '✨ Compartilhe uma experiência de liderança',
      '💫 Como você desenvolve líderes?',
      '🙏 Que princípio de liderança mais te marca?',
      '💭 Como você forma sua equipe?',
      '🌟 Qual sua maior lição de liderança?',
      '💪 Como você lidera pelo exemplo?',
      '📖 Que versículo sobre liderança te inspira?',
      '🎯 Que área você quer desenvolver?',
      '💫 Como você multiplica líderes?',
      '🙌 Que líder te inspira?',
      '❤️ Como a liderança te transforma?',
      '🌟 Que experiência te marcou?',
      '💭 Como você serve sua equipe?'
    ],
    hashtags: [
      '#Lideranca #LiderancaCrista #LiderServidor',
      '#LiderancaServa #FormandoLideres #Influencia',
      '#LiderancaEfetiva #DesenvolvimentoDeLideres #Mentoria',
      '#LiderancaTransformadora #LiderancaDeValor #Multiplicacao',
      '#LiderancaPositiva #LiderancaInspiradora #ImpactoPositivo'
    ]
  },
  'Comunhão': {
    inicio: [
      'Unidos somos mais fortes.',
      'A comunhão fortalece a fé.',
      'Juntos crescemos mais.',
      'A comunhão é essencial.',
      'Unidos em Cristo.',
      'A comunhão traz crescimento.',
      'Juntos somos igreja.',
      'A comunhão aproxima corações.',
      'Unidos no mesmo propósito.',
      'A comunhão é vida.',
      'Unidos em amor.',
      'A comunhão transforma.',
      'Juntos vamos mais longe.',
      'A comunhão é bênção.',
      'Unidos em espírito.'
    ],
    meio: [
      'Na comunhão encontramos força.',
      'Unidos vencemos mais.',
      'A comunhão traz cura.',
      'Juntos somos melhores.',
      'A comunhão fortalece laços.',
      'Unidos em amor.',
      'A comunhão transforma vidas.',
      'Juntos alcançamos mais.',
      'A comunhão é fundamental.',
      'Unidos em propósito.',
      'A comunhão renova.',
      'Unidos crescemos.',
      'A comunhão edifica.',
      'Juntos somos um.',
      'A comunhão fortalece.'
    ],
    fim: [
      'Busque a comunhão verdadeira.',
      'Fortaleça seus relacionamentos.',
      'Viva em comunidade.',
      'Cultive amizades profundas.',
      'Seja parte da família.',
      'Invista em relacionamentos.',
      'Cresça em comunhão.',
      'Viva conectado.',
      'Fortaleça a unidade.',
      'Seja família.',
      'A comunhão transforma.',
      'Unidos somos mais.',
      'Viva em unidade.',
      'Cultive a comunhão.',
      'Seja comunidade.'
    ],
    cta: [
      '🤝 Como você cultiva comunhão?',
      '❤️ O que a comunhão significa para você?',
      '✨ Compartilhe uma experiência de comunhão',
      '💫 Como você fortalece relacionamentos?',
      '🙏 Vamos crescer juntos?',
      '💭 Que momento de comunhão te marcou?',
      '🌟 Como você vive em comunidade?',
      '👥 Marque seu grupo de comunhão',
      '💝 Como você investe em amizades?',
      '🎯 Que área você quer fortalecer?',
      '💫 Como você cultiva unidade?',
      '🙌 Que experiência de comunhão te marcou?',
      '❤️ Como a comunhão te transforma?',
      '🌟 Que momento especial você viveu?',
      '💭 Como você fortalece laços?'
    ],
    hashtags: [
      '#Comunhao #VidaEmComunidade #UnidosEmCristo',
      '#ComunhaoVerdadeira #VidaEmIgreja #Unidade',
      '#ComunhaoFraternal #RelacionamentosCristaos #Igreja',
      '#ComunhaoEFe #VidaEmFamilia #Relacionamentos',
      '#ComunhaoDiaria #FamiliaDaFe #UnidosNoAmor'
    ]
  },
  'Ministério': {
    inicio: [
      'Servir é um privilégio.',
      'Cada um tem um ministério.',
      'O ministério é para todos.',
      'Sirva com excelência.',
      'Seu dom é importante.',
      'Ministério é serviço.',
      'Use seus dons para Deus.',
      'Sirva com amor.',
      'Ministério é propósito.',
      'Você foi chamado para servir.',
      'Ministério é dedicação.',
      'Sirva com alegria.',
      'Seu ministério é único.',
      'Use seus talentos.',
      'Ministério é vocação.'
    ],
    meio: [
      'Sirva com dedicação.',
      'Seu ministério impacta vidas.',
      'Use seus talentos.',
      'Sirva com alegria.',
      'Ministério é compromisso.',
      'Faça a diferença.',
      'Seu serviço é valioso.',
      'Ministre com graça.',
      'Seja fiel no pouco.',
      'Deus usa pessoas disponíveis.',
      'Ministério é serviço.',
      'Sirva com excelência.',
      'Seu dom faz diferença.',
      'Use seus dons.',
      'Ministério é amor.'
    ],
    fim: [
      'Desenvolva seu ministério.',
      'Sirva com excelência.',
      'Seja fiel no servir.',
      'Impacte vidas.',
      'Cresça no ministério.',
      'Multiplique seus dons.',
      'Deixe sua marca.',
      'Sirva com propósito.',
      'Seja um servo fiel.',
      'Faça a diferença.',
      'Seu ministério importa.',
      'Sirva com dedicação.',
      'Seja um exemplo.',
      'Impacte gerações.',
      'Ministério que transforma.'
    ],
    cta: [
      '🎯 Como você serve no Reino?',
      '❤️ Qual seu ministério?',
      '✨ Compartilhe seu testemunho ministerial',
      '💫 Como você usa seus dons?',
      '🙏 Que área você quer servir?',
      '💭 Como você desenvolve seu ministério?',
      '🌟 Que dom você quer multiplicar?',
      '👥 Como você impacta vidas?',
      '💝 Marque alguém que serve bem',
      '📖 Qual sua visão ministerial?',
      '💫 Como você serve a Deus?',
      '🙌 Que experiência ministerial te marcou?',
      '❤️ Como o ministério te transforma?',
      '🌟 Que área você mais gosta de servir?',
      '💭 Como você usa seus dons?'
    ],
    hashtags: [
      '#Ministerio #ServicoADeus #DonsEMinisterios',
      '#MinisterioCristao #ServirADeus #Vocacao',
      '#MinisterioEfetivo #ServicoAoReino #Proposito',
      '#MinisterioEFe #ServirComAmor #ImpactoMinisterial',
      '#MinisterioTransformador #ServicoFiel #Reino'
    ]
  }
};

export function gerarIdeiaAleatoria(tema: string = ''): {
  titulo: string;
  reflexao: string;
  cta: string;
  hashtags: string;
} {
  const temas = Object.keys(templates);
  const temaEscolhido = tema || temas[Math.floor(Math.random() * temas.length)];
  const template = templates[temaEscolhido];

  const inicio = template.inicio[Math.floor(Math.random() * template.inicio.length)];
  const meio = template.meio[Math.floor(Math.random() * template.meio.length)];
  const fim = template.fim[Math.floor(Math.random() * template.fim.length)];
  const cta = template.cta[Math.floor(Math.random() * template.cta.length)];
  const hashtags = template.hashtags[Math.floor(Math.random() * template.hashtags.length)];

  return {
    titulo: temaEscolhido,
    reflexao: `${inicio}\n\n${meio}\n\n${fim}`,
    cta: cta,
    hashtags: hashtags
  };
} 